import React from 'react';
import './Experience.css';

const Experience: React.FC = () => {
  return (
    <section id="experience">
      <p className="section__text__p1">Explore My</p>
      <h1 className="title">Experience</h1>
      <div className="experience-details-container">
        <div className="about-containers">
          <div className="details-container">
            <h2 className="experience-sub-title">Frontend Development</h2>
            <div className="article-container">
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>HTML5</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>CSS3</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>Sass</h3>
                  <p>Intermediate</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>JavaScript</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>React.js</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>TypeScript</h3>
                  <p>Basic</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>Java</h3>
                  <p>Intermediate</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>C</h3>
                  <p>Experiaced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>C++</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>PHP</h3>
                  <p>Experienced</p>
                </div>
              </article>
            </div>
          </div>
          <div className="details-container">
            <h2 className="experience-sub-title">Backend Development</h2>
            <div className="article-container">
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>Node.js</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>Express.js</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>MongoDB</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>MySQL</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>Git</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>phpMyAdmin</h3>
                  <p>Experienced</p>
                </div>
              </article>
              <article>
                <img
                  src="/assets/checkmark.png"
                  alt="Checkmark"
                  className="icon"
                />
                <div>
                  <h3>XAMPP</h3>
                  <p>Experienced</p>
                </div>
              </article>
            </div>
          </div>
        </div>
      </div>
      <img
        src="/assets/arrow.png"
        alt="Arrow"
        className="icon arrow"
        onClick={() => window.location.href = '#projects'}
      />
    </section>
  );
};

export default Experience; 